//@ui5-bundle ui5boot/splash/Component-preload.js
sap.ui.predefine("ui5boot/splash/Component", ["sap/ui/core/UIComponent","./model/models"],(e,t)=>{"use strict";return e.extend("ui5boot.splash.Component",{metadata:{manifest:"json"},init(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
sap.ui.predefine("ui5boot/splash/controller/App.controller", ["./BaseController"],function(n){"use strict";return n.extend("ui5boot.splash.controller.App",{onInit:function(){}})});
sap.ui.predefine("ui5boot/splash/controller/BaseController", ["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/ui/core/routing/History"],function(e,t,n){"use strict";return e.extend("ui5boot.splash.controller.BaseController",{getOwnerComponent:function(){return e.prototype.getOwnerComponent.call(this)},getRouter:function(){return t.getRouterFor(this)},getResourceBundle:function(){const e=this.getOwnerComponent().getModel("i18n");return e.getResourceBundle()},getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){this.getView().setModel(e,t);return this},navTo:function(e,t,n){this.getRouter().navTo(e,t,undefined,n)},onNavBack:function(){const e=n.getInstance().getPreviousHash();if(e!==undefined){window.history.go(-1)}else{this.getRouter().navTo("main",{},undefined,true)}}})});
sap.ui.predefine("ui5boot/splash/controller/Main.controller", ["./BaseController","sap/m/MessageBox"],function(e,o){"use strict";return e.extend("ui5boot.splash.controller.Main",{sayHello:function(){o.show("Hello World!")}})});
sap.ui.predefine("ui5boot/splash/model/formatter", function(){"use strict";return{formatValue:function(e){return e&&e.toUpperCase()}}});
sap.ui.predefine("ui5boot/splash/model/models", ["sap/ui/model/json/JSONModel","sap/ui/model/BindingMode","sap/ui/Device"],function(e,n,i){"use strict";return{createDeviceModel:function(){const o=new e(i);o.setDefaultBindingMode(n.OneWay);return o}}});
sap.ui.require.preload({
	"ui5boot/splash/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"ui5boot.splash","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"ui5boot.splash.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.120.21","libs":{"sap.ui.core":{},"sap.m":{}}},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"ui5boot.splash.i18n.i18n"}}},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"ui5boot.splash.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"main","target":"main"}],"targets":{"main":{"viewId":"main","viewName":"Main"}}}}}',
	"ui5boot/splash/view/App.view.xml":'<mvc:View\n\tcontrollerName="ui5boot.splash.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><App id="app" /></mvc:View>\n',
	"ui5boot/splash/view/Main.view.xml":'<mvc:View\n\tcontrollerName="ui5boot.splash.controller.Main"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:core="sap.ui.core"\n\tcore:require="{\n\t\tformatter: \'ui5boot/splash/model/formatter\'\n\t}"><Page\n\t\ttitle="{i18n>appTitle}"\n\t\tid="page"><content><IllustratedMessage\n\t\t\t\ttitle="{i18n>appTitle}"\n\t\t\t\tillustrationType="sapIllus-SuccessHighFive"\n\t\t\t\tenableVerticalResponsiveness="true"\n\t\t\t\tdescription="{i18n>appDescription}"><additionalContent><Button\n\t\t\t\t\t\tid="helloButton"\n\t\t\t\t\t\ttext="{formatter: \'formatter.formatValue\', path: \'i18n>btnText\'}"\n\t\t\t\t\t\tpress="sayHello" /></additionalContent></IllustratedMessage></content></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
